# SAT-ACT EDA
___

In [1]:
# Imports
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
# reads
act17 = pd.read_csv('../../Data/ACT-SAT/act_2017.csv')
act18 = pd.read_csv('../../Data/ACT-SAT/act_2018.csv')
sat17 = pd.read_csv('../../Data/ACT-SAT/sat_2017.csv')
sat18 = pd.read_csv('../../Data/ACT-SAT/sat_2018.csv')

In [3]:
act17.head()

State Participation  English  Math  Reading  Science Composite
0  National           60%     20.3  20.7     21.4     21.0      21.0
1   Alabama          100%     18.9  18.4     19.7     19.4      19.2
2    Alaska           65%     18.7  19.8     20.4     19.9      19.8
3   Arizona           62%     18.6  19.8     20.1     19.8      19.7
4  Arkansas          100%     18.9  19.0     19.7     19.5      19.4

In [4]:
act17.dtypes

State             object
Participation     object
English          float64
Math             float64
Reading          float64
Science          float64
Composite         object
dtype: object

In [5]:
act17[act17['Composite'] == '20.2x']

State Participation  English  Math  Reading  Science Composite
51  Wyoming          100%     19.4  19.8     20.8     20.6     20.2x

In [6]:
# fixing erroneous data
act17.loc[51, ['Composite']] = 20.2

act17['Composite'] = act17['Composite'].astype(float)

In [7]:
act17.dtypes

State             object
Participation     object
English          float64
Math             float64
Reading          float64
Science          float64
Composite        float64
dtype: object

In [8]:
# change Participation into numerical data
act17['Participation'] = [int(num.split('%')[0])/100 for num in act17['Participation']]

In [9]:
act17.dtypes

State             object
Participation    float64
English          float64
Math             float64
Reading          float64
Science          float64
Composite        float64
dtype: object

In [10]:
act17.head()

State  Participation  English  Math  Reading  Science  Composite
0  National           0.60     20.3  20.7     21.4     21.0       21.0
1   Alabama           1.00     18.9  18.4     19.7     19.4       19.2
2    Alaska           0.65     18.7  19.8     20.4     19.9       19.8
3   Arizona           0.62     18.6  19.8     20.1     19.8       19.7
4  Arkansas           1.00     18.9  19.0     19.7     19.5       19.4

In [30]:
act17.describe()

Participation    English       Math    Reading    Science  Composite
count      52.000000  52.000000  52.000000  52.000000  52.000000  52.000000
mean        0.651538  20.919231  21.173077  22.001923  21.040385  21.509615
std         0.318325   2.332132   1.963602   2.048672   3.151113   2.002083
min         0.080000  16.300000  18.000000  18.100000   2.300000  17.800000
25%         0.310000  19.000000  19.400000  20.475000  19.900000  19.800000
50%         0.680000  20.550000  20.900000  21.700000  21.150000  21.400000
75%         1.000000  23.300000  23.100000  24.125000  22.525000  23.600000
max         1.000000  25.500000  25.300000  26.000000  24.900000  25.500000

In [33]:
act17.sort_values('Science').head()

State  Participation  English  Math  Reading  Science  Composite
21        Maryland           0.28     23.3  23.1     24.2      2.3       23.6
29          Nevada           1.00     16.3  18.0     18.1     18.2       17.8
25     Mississippi           1.00     18.2  18.1     18.8     18.8       18.6
41  South Carolina           1.00     17.5  18.6     19.1     18.9       18.7
34  North Carolina           1.00     17.8  19.3     19.6     19.3       19.1

according to our [source](https://www.act.org/content/dam/act/unsecured/documents/cccr2017/ACT_2017-Average_Scores_by_State.pdf) Maryland's Science score should be 23.2

In [36]:
act17.loc[act17['State'] == 'Maryland', ['Science']] = 23.2

In [37]:
act17.describe()

Participation    English       Math    Reading    Science  Composite
count      52.000000  52.000000  52.000000  52.000000  52.000000  52.000000
mean        0.651538  20.919231  21.173077  22.001923  21.442308  21.509615
std         0.318325   2.332132   1.963602   2.048672   1.723351   2.002083
min         0.080000  16.300000  18.000000  18.100000  18.200000  17.800000
25%         0.310000  19.000000  19.400000  20.475000  19.975000  19.800000
50%         0.680000  20.550000  20.900000  21.700000  21.300000  21.400000
75%         1.000000  23.300000  23.100000  24.125000  23.200000  23.600000
max         1.000000  25.500000  25.300000  26.000000  24.900000  25.500000

In [54]:
act17.shape

(52, 7)

___

In [11]:
act18.head()

State Participation  Composite
0     Alabama          100%       19.1
1      Alaska           33%       20.8
2     Arizona           66%       19.2
3    Arkansas          100%       19.4
4  California           27%       22.7

In [12]:
act18.dtypes

State             object
Participation     object
Composite        float64
dtype: object

In [13]:
# converting Participation to numerical data
act18['Participation'] = [int(num.split('%')[0])/100 for num in act18['Participation']]

In [14]:
act18.dtypes

State             object
Participation    float64
Composite        float64
dtype: object

In [15]:
act18.loc[act18['State'] == 'Maine']

State  Participation  Composite
19  Maine           0.07       24.0
20  Maine           0.07       24.0

In [16]:
act18 = act18.drop(19, axis=0).reset_index(drop=True)

In [17]:
act18.shape

(51, 3)

In [38]:
act18.describe()

Participation  Composite
count      51.000000  51.000000
mean        0.617255  21.496078
std         0.340371   2.111583
min         0.070000  17.700000
25%         0.285000  19.950000
50%         0.660000  21.300000
75%         1.000000  23.650000
max         1.000000  25.600000

according to our [source](https://www.act.org/content/dam/act/unsecured/documents/cccr2018/Average-Scores-by-State.pdf) the national participation rate was 55% and the average composite score was 20.8

In [49]:
act18nat = pd.DataFrame([{'State': 'National', 'Participation': .55, 'Composite': 20.8}])
act18nat

State  Participation  Composite
0  National           0.55       20.8

In [53]:
act18 = pd.concat([act18nat, act18], ignore_index=True)

In [56]:
act18.head()

State  Participation  Composite
0  National           0.55       20.8
1   Alabama           1.00       19.1
2    Alaska           0.33       20.8
3   Arizona           0.66       19.2
4  Arkansas           1.00       19.4

In [55]:
act18.shape

(52, 3)

___

In [18]:
sat17.head()

State Participation  Evidence-Based Reading and Writing  Math  Total
0     Alabama            5%                                 593   572   1165
1      Alaska           38%                                 547   533   1080
2     Arizona           30%                                 563   553   1116
3    Arkansas            3%                                 614   594   1208
4  California           53%                                 531   524   1055

In [57]:
sat17.shape

(51, 5)

In [19]:
sat17.dtypes

State                                 object
Participation                         object
Evidence-Based Reading and Writing     int64
Math                                   int64
Total                                  int64
dtype: object

In [20]:
sat17['Participation'] = [int(num.split('%')[0])/100 for num in sat17['Participation']]

In [21]:
sat17.dtypes

State                                  object
Participation                         float64
Evidence-Based Reading and Writing      int64
Math                                    int64
Total                                   int64
dtype: object

In [22]:
sat17.describe()

Participation  Evidence-Based Reading and Writing        Math  \
count      51.000000                           51.000000   51.000000   
mean        0.398039                          569.117647  547.627451   
std         0.352766                           45.666901   84.909119   
min         0.020000                          482.000000   52.000000   
25%         0.040000                          533.500000  522.000000   
50%         0.380000                          559.000000  548.000000   
75%         0.660000                          613.000000  599.000000   
max         1.000000                          644.000000  651.000000   

             Total  
count    51.000000  
mean   1126.098039  
std      92.494812  
min     950.000000  
25%    1055.500000  
50%    1107.000000  
75%    1212.000000  
max    1295.000000

In [23]:
sat17.loc[sat17['Math'] < 400]

State  Participation  Evidence-Based Reading and Writing  Math  Total
20  Maryland           0.69                                 536    52   1060

according to our [source](https://blog.collegevine.com/here-are-the-average-sat-scores-by-state/) Maryland's Math score should be 524

In [24]:
sat17.loc[20,['Math']] = 524

In [25]:
sat17.describe()

Participation  Evidence-Based Reading and Writing        Math  \
count      51.000000                           51.000000   51.000000   
mean        0.398039                          569.117647  556.882353   
std         0.352766                           45.666901   47.121395   
min         0.020000                          482.000000  468.000000   
25%         0.040000                          533.500000  523.500000   
50%         0.380000                          559.000000  548.000000   
75%         0.660000                          613.000000  599.000000   
max         1.000000                          644.000000  651.000000   

             Total  
count    51.000000  
mean   1126.098039  
std      92.494812  
min     950.000000  
25%    1055.500000  
50%    1107.000000  
75%    1212.000000  
max    1295.000000

___

In [26]:
sat18.head()

State Participation  Evidence-Based Reading and Writing  Math  Total
0     Alabama            6%                                 595   571   1166
1      Alaska           43%                                 562   544   1106
2     Arizona           29%                                 577   572   1149
3    Arkansas            5%                                 592   576   1169
4  California           60%                                 540   536   1076

In [27]:
sat18.dtypes

State                                 object
Participation                         object
Evidence-Based Reading and Writing     int64
Math                                   int64
Total                                  int64
dtype: object

In [28]:
sat18['Participation'] = [int(num.split('%')[0])/100 for num in sat18['Participation']]

In [29]:
sat18.describe()

Participation  Evidence-Based Reading and Writing        Math  \
count      51.000000                           51.000000   51.000000   
mean        0.457451                          563.686275  556.235294   
std         0.373143                           47.502627   47.772623   
min         0.020000                          480.000000  480.000000   
25%         0.045000                          534.500000  522.500000   
50%         0.520000                          552.000000  544.000000   
75%         0.775000                          610.500000  593.500000   
max         1.000000                          643.000000  655.000000   

             Total  
count    51.000000  
mean   1120.019608  
std      94.155083  
min     977.000000  
25%    1057.500000  
50%    1098.000000  
75%    1204.000000  
max    1298.000000